### ISSUE TITLE
Tip 227: Cache Accessor Result

### ISSUE THREAD

**Issue by andrey-helldar** [OussamaMater/Laravel-Tips#11]
Attribute does not have a `shouldCache` parameter. Anyway, Laravel 11.36.1.

- https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Eloquent/Casts/Attribute.php#L55-L58
- https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Eloquent/Casts/Attribute.php#L99-L104

```diff
 protected function hash(): Attribute
 {
     return Attribute::make(
         get: fn (string $value) => bcrypt(gzuncompress($value)),
-        shouldCache: true
-    );
+    )->shouldCache();
 }
```

**Comment by OussamaMater** [comment]
Thanks, good catch! I fixed it.
